<a href="https://colab.research.google.com/github/mansisinha/taddhita/blob/master/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
!pip install -q xlrd
!git clone https://github.com/mansisinha/taddhita.git

fatal: destination path 'taddhita' already exists and is not an empty directory.

In [103]:
!ls taddhita/newPairs.txt

taddhita/newPairs.txt

In [104]:
import pandas as pd
url='https://raw.githubusercontent.com/mansisinha/taddhita/master/allPairs.csv'

df=pd.read_csv(url)
df
df.groupby('affix').count()

,word,sense,meaning,Affix,Source Word,Source Word Count,Derived Word,Derived word count,word_y
affix,,,,,,,,,
age,13,13,13,13,13,13,13,13,13
al,84,84,84,84,84,84,84,84,84
ally,199,199,199,199,199,199,199,199,199
an,12,12,12,12,12,12,12,12,12
ation,109,109,109,109,109,109,109,109,109
dom,14,14,14,14,14,14,14,14,14
ee,70,70,70,70,70,70,70,70,70
en,33,33,33,33,33,33,33,33,33
er,1425,1425,1425,1425,1425,1425,1425,1425,1425
ess,18,18,18,18,18,18,18,18,18
ette,12,12,12,12,12,12,12,12,12
ful,52,52,52,52,52,52,52,52,52
hood,39,39,39,39,39,39,39,39,39
ian,15,15,15,15,15,15,15,15,15
ic,402,402,402,402,402,402,402,402,402
ical,87,87,87,87,87,87,87,87,87
ie,24,24,24,24,24,24,24,24,24
ion,31,31,31,31,31,31,31,31,31
ise,13,13,13,13,13,13,13,13,13
ish,129,129,129,129,129,129,129,129,129
ism,175,175,175,175,175,175,175,175,175
ist,349,349,349,349,349,349,349,349,349
ity,237,237,237,237,237,237,237,237,237
ive,17,17,17,17,17,17,17,17,17
ize,69,69,69,69,69,69,69,69,69
le,12,12,12,12,12,12,12,12,12
less,14,14,14,14,14,14,14,14,14
let,42,42,42,42,42,42,42,42,42
like,173,173,173,173,173,173,173,173,173
ling,33,33,33,33,33,33,33,33,33
ly,1880,1880,1880,1880,1880,1880,1880,1880,1880
man,115,115,115,115,115,115,115,115,115
ment,104,104,104,104,104,104,104,104,104
ness,998,998,998,998,998,998,998,998,998
o,18,18,18,18,18,18,18,18,18
oid,37,37,37,37,37,37,37,37,37
or,107,107,107,107,107,107,107,107,107
ous,23,23,23,23,23,23,23,23,23
proof,17,17,17,17,17,17,17,17,17
ship,80,80,80,80,80,80,80,80,80
ster,31,31,31,31,31,31,31,31,31
wise,34,34,34,34,34,34,34,34,34
y,169,169,169,169,169,169,169,169,169

In [105]:
import pandas as pd
df2=pd.read_csv('taddhita/newPairs.txt',header=None)
df2

                0               1      2
0            Free         Freeman    man
1            Free         Freedom    dom
2              of            ofor     or
3              of            ofer     er
4              of            ofan     an
5             the           theic     ic
6             the          theism    ism
7             the         thester   ster
8             the          theist    ist
9             the            theo      o
10            the           theer     er
11            the          thedom    dom
12            the           theie     ie
13            the            they      y
14            the          theion    ion
15             is          isness   ness
16             is             iso      o
17             is            isle     le
18             is            iser     er
19             is         isation  ation
20             is            isen     en
21             is           islet    let
22             is            isan     an
23            not         notness   ness
24            not           notor     or
25            not          notist    ist
26            not            noto      o
27            not           noter     er
28            not           notal     al
29            not          notian    ian
...           ...             ...    ...
14455        zien          ziener     er
14456  suspension  suspensionless   less
14457       demur        demurity    ity
14458       demur         demurer     er
14459        suit        suitless   less
14460        suit          suitor     or
14461        suit           suito      o
14462        suit          suiter     er
14463        suit        suitlike   like
14464        suit          suiten     en
14465         mop           mopee     ee
14466         mop            mopo      o
14467         mop           moper     er
14468         mop            mopy      y
14469         mop         moplike   like
14470         mop          mopish    ish
14471       humid       humidness   ness
14472       humid         humidor     or
14473       humid        humidity    ity
14474       humid          humido      o
14475       humid         humider     er
14476       humid         humidly     ly
14477    moisture    moistureless   less
14478    moisture   moistureproof  proof
14479    backlash      backlasher     er
14480        lash        lashless   less
14481        lash           lasho      o
14482        lash          lasher     er
14483        lash        lashlike   like
14484        lash        lashwise   wise

[14485 rows x 3 columns]

In [106]:
df2.groupby(2).count()

          0     1
2
affix     3     3
age     214   214
al      377   377
ally    123   123
an      649   648
ation   118   118
dom     118   118
ee      206   206
en      996   996
er     1289  1289
ess     106   106
ette    123   123
ful     225   225
hood    163   163
ian     189   189
ic      206   206
ical     46    46
ie      384   384
ion     149   149
ise     237   237
ish     361   361
ism     276   276
ist     287   287
ity     132   132
ive      94    94
ize     247   247
le      276   276
less    829   829
let     203   203
like    746   746
ling    290   290
ly      730   730
man     334   334
ment    192   192
ness    672   672
o      1047  1047
oid      86    86
or      366   366
ous     119   119
proof    94    94
ship    125   125
ster    142   142
wise    129   129
y       787   787

In [107]:
df2['n']=0
df2

                0               1      2  n
0            Free         Freeman    man  0
1            Free         Freedom    dom  0
2              of            ofor     or  0
3              of            ofer     er  0
4              of            ofan     an  0
5             the           theic     ic  0
6             the          theism    ism  0
7             the         thester   ster  0
8             the          theist    ist  0
9             the            theo      o  0
10            the           theer     er  0
11            the          thedom    dom  0
12            the           theie     ie  0
13            the            they      y  0
14            the          theion    ion  0
15             is          isness   ness  0
16             is             iso      o  0
17             is            isle     le  0
18             is            iser     er  0
19             is         isation  ation  0
20             is            isen     en  0
21             is           islet    let  0
22             is            isan     an  0
23            not         notness   ness  0
24            not           notor     or  0
25            not          notist    ist  0
26            not            noto      o  0
27            not           noter     er  0
28            not           notal     al  0
29            not          notian    ian  0
...           ...             ...    ... ..
14455        zien          ziener     er  0
14456  suspension  suspensionless   less  0
14457       demur        demurity    ity  0
14458       demur         demurer     er  0
14459        suit        suitless   less  0
14460        suit          suitor     or  0
14461        suit           suito      o  0
14462        suit          suiter     er  0
14463        suit        suitlike   like  0
14464        suit          suiten     en  0
14465         mop           mopee     ee  0
14466         mop            mopo      o  0
14467         mop           moper     er  0
14468         mop            mopy      y  0
14469         mop         moplike   like  0
14470         mop          mopish    ish  0
14471       humid       humidness   ness  0
14472       humid         humidor     or  0
14473       humid        humidity    ity  0
14474       humid          humido      o  0
14475       humid         humider     er  0
14476       humid         humidly     ly  0
14477    moisture    moistureless   less  0
14478    moisture   moistureproof  proof  0
14479    backlash      backlasher     er  0
14480        lash        lashless   less  0
14481        lash           lasho      o  0
14482        lash          lasher     er  0
14483        lash        lashlike   like  0
14484        lash        lashwise   wise  0

[14485 rows x 4 columns]

In [108]:
df['indf']=1
df3=pd.merge(df2,df,how='left',left_on=[0,1,2],right_on=['Source Word','Derived Word','Affix'])
df3['n']=df3['n']+df3['indf'].fillna(0)
df3.drop(['Source Word','Derived Word','Affix','affix','word','sense','meaning','Source Word Count','Derived word count','word_y','indf'],axis=1,inplace=True)
df3.columns=['source_word','derived_word','affix','n']
df3

      source_word    derived_word  affix    n
0            Free         Freeman    man  0.0
1            Free         Freedom    dom  0.0
2              of            ofor     or  0.0
3              of            ofer     er  0.0
4              of            ofan     an  0.0
5             the           theic     ic  0.0
6             the          theism    ism  0.0
7             the         thester   ster  0.0
8             the          theist    ist  0.0
9             the            theo      o  0.0
10            the           theer     er  0.0
11            the          thedom    dom  0.0
12            the           theie     ie  0.0
13            the            they      y  0.0
14            the          theion    ion  0.0
15             is          isness   ness  1.0
16             is             iso      o  0.0
17             is            isle     le  0.0
18             is            iser     er  0.0
19             is         isation  ation  0.0
20             is            isen     en  0.0
21             is           islet    let  0.0
22             is            isan     an  0.0
23            not         notness   ness  0.0
24            not           notor     or  0.0
25            not          notist    ist  0.0
26            not            noto      o  0.0
27            not           noter     er  0.0
28            not           notal     al  0.0
29            not          notian    ian  0.0
...           ...             ...    ...  ...
14455        zien          ziener     er  0.0
14456  suspension  suspensionless   less  0.0
14457       demur        demurity    ity  0.0
14458       demur         demurer     er  0.0
14459        suit        suitless   less  0.0
14460        suit          suitor     or  0.0
14461        suit           suito      o  0.0
14462        suit          suiter     er  0.0
14463        suit        suitlike   like  0.0
14464        suit          suiten     en  0.0
14465         mop           mopee     ee  0.0
14466         mop            mopo      o  0.0
14467         mop           moper     er  0.0
14468         mop            mopy      y  0.0
14469         mop         moplike   like  0.0
14470         mop          mopish    ish  0.0
14471       humid       humidness   ness  0.0
14472       humid         humidor     or  0.0
14473       humid        humidity    ity  0.0
14474       humid          humido      o  0.0
14475       humid         humider     er  0.0
14476       humid         humidly     ly  0.0
14477    moisture    moistureless   less  0.0
14478    moisture   moistureproof  proof  0.0
14479    backlash      backlasher     er  0.0
14480        lash        lashless   less  0.0
14481        lash           lasho      o  0.0
14482        lash          lasher     er  1.0
14483        lash        lashlike   like  0.0
14484        lash        lashwise   wise  0.0

[14485 rows x 4 columns]

In [109]:
df3.groupby('n').count()

     source_word  derived_word  affix
n
0.0        13447         13446  13447
1.0         1038          1038   1038

In [110]:
df3['counts']=df3.groupby('affix')['n'].transform('count')
df3['m']=1
cols=['affix','n','counts']
cols1=['m']
df3[['{}_sum'.format(x) for x in cols1]] = df3.groupby(cols)[cols1].transform('sum')
df3=df3.sort_values('counts')
df3

      source_word   derived_word  affix    n  counts  m  m_sum
8473           re        reaffix  affix  0.0     3.0  1      3
2247          non       nonaffix  affix  0.0     3.0  1      3
4541         tree      treeaffix  affix  0.0     3.0  1      3
12912       meter      meterical   ical  0.0    46.0  1     44
9827     linguist   linguistical   ical  0.0    46.0  1     44
7516           ba         baical   ical  0.0    46.0  1     44
2361       system     systemical   ical  0.0    46.0  1     44
6179          met        metical   ical  0.0    46.0  1     44
5931          ant        antical   ical  0.0    46.0  1     44
10508    metaphor   metaphorical   ical  0.0    46.0  1     44
346       synonym    synonymical   ical  0.0    46.0  1     44
6620    astronaut  astronautical   ical  0.0    46.0  1     44
2159          cod        codical   ical  0.0    46.0  1     44
10580         sin        sinical   ical  0.0    46.0  1     44
2469         Arab       Arabical   ical  0.0    46.0  1     44
13072    electron   electronical   ical  0.0    46.0  1     44
806       Abraham    Abrahamical   ical  0.0    46.0  1     44
13218      analog     analogical   ical  0.0    46.0  1     44
362       dialect    dialectical   ical  0.0    46.0  1     44
13207     monarch    monarchical   ical  1.0    46.0  1      2
8615       Darwin     Darwinical   ical  0.0    46.0  1     44
1274          log        logical   ical  0.0    46.0  1     44
12370       heart      heartical   ical  0.0    46.0  1     44
12551       fluid      fluidical   ical  0.0    46.0  1     44
13174       organ      organical   ical  0.0    46.0  1     44
12767     stomach    stomachical   ical  0.0    46.0  1     44
8384        angel      angelical   ical  0.0    46.0  1     44
10994   charlatan  charlatanical   ical  0.0    46.0  1     44
9050          fin        finical   ical  0.0    46.0  1     44
8026         vert       vertical   ical  0.0    46.0  1     44
...           ...            ...    ...  ...     ... ..    ...
926            nu           nuer     er  0.0  1289.0  1   1110
6931          pen          pener     er  0.0  1289.0  1   1110
3615       Brunei       Bruneier     er  0.0  1289.0  1   1110
9933         hurt         hurter     er  0.0  1289.0  1   1110
9927         hold         holder     er  0.0  1289.0  1   1110
2497      Zealand      Zealander     er  0.0  1289.0  1   1110
13149       baron        baroner     er  0.0  1289.0  1   1110
13142     empress      empresser     er  0.0  1289.0  1   1110
6650   experiment   experimenter     er  0.0  1289.0  1   1110
879            on           oner     er  0.0  1289.0  1   1110
9891         hang         hanger     er  1.0  1289.0  1    179
7701          ban          baner     er  0.0  1289.0  1   1110
1533          can          caner     er  0.0  1289.0  1   1110
9897         hung         hunger     er  0.0  1289.0  1   1110
5959     argument     argumenter     er  0.0  1289.0  1   1110
9902          had          hader     er  0.0  1289.0  1   1110
11866         ven          vener     er  0.0  1289.0  1   1110
893       abscond      absconder     er  0.0  1289.0  1   1110
4600       Korean       Koreaner     er  0.0  1289.0  1   1110
13117        vein         veiner     er  0.0  1289.0  1   1110
9913          hid          hider     er  0.0  1289.0  1   1110
7691        mulch        mulcher     er  0.0  1289.0  1   1110
9923          hit          hiter     er  0.0  1289.0  1   1110
13109       orbit        orbiter     er  1.0  1289.0  1    179
896     absconder    absconderer     er  0.0  1289.0  1   1110
5972          arm          armer     er  0.0  1289.0  1   1110
7687         soil         soiler     er  1.0  1289.0  1    179
899           odd          odder     er  0.0  1289.0  1   1110
2473         Arab         Araber     er  0.0  1289.0  1   1110
11834     microbe      microbeer     er  0.0  1289.0  1   1110

[14485 rows x 7 columns]

In [112]:

df3.loc[~(df3['counts']<10)]
df4=df3.loc[~((df3['n']!=1) & (df3['m_sum']<5))]
df_final=df4.drop(['n','counts','m','m_sum'],axis=1)
df_final.reset_index()
df_final

      source_word   derived_word affix
12912       meter      meterical  ical
9827     linguist   linguistical  ical
7516           ba         baical  ical
2361       system     systemical  ical
6179          met        metical  ical
5931          ant        antical  ical
10508    metaphor   metaphorical  ical
346       synonym    synonymical  ical
6620    astronaut  astronautical  ical
2159          cod        codical  ical
10580         sin        sinical  ical
2469         Arab       Arabical  ical
13072    electron   electronical  ical
806       Abraham    Abrahamical  ical
13218      analog     analogical  ical
362       dialect    dialectical  ical
13207     monarch    monarchical  ical
8615       Darwin     Darwinical  ical
1274          log        logical  ical
12370       heart      heartical  ical
12551       fluid      fluidical  ical
13174       organ      organical  ical
12767     stomach    stomachical  ical
8384        angel      angelical  ical
10994   charlatan  charlatanical  ical
9050          fin        finical  ical
8026         vert       vertical  ical
8096       pedant     pedantical  ical
9609         icon       iconical  ical
5981          art        artical  ical
...           ...            ...   ...
926            nu           nuer    er
6931          pen          pener    er
3615       Brunei       Bruneier    er
9933         hurt         hurter    er
9927         hold         holder    er
2497      Zealand      Zealander    er
13149       baron        baroner    er
13142     empress      empresser    er
6650   experiment   experimenter    er
879            on           oner    er
9891         hang         hanger    er
7701          ban          baner    er
1533          can          caner    er
9897         hung         hunger    er
5959     argument     argumenter    er
9902          had          hader    er
11866         ven          vener    er
893       abscond      absconder    er
4600       Korean       Koreaner    er
13117        vein         veiner    er
9913          hid          hider    er
7691        mulch        mulcher    er
9923          hit          hiter    er
13109       orbit        orbiter    er
896     absconder    absconderer    er
5972          arm          armer    er
7687         soil         soiler    er
899           odd          odder    er
2473         Arab         Araber    er
11834     microbe      microbeer    er

[14482 rows x 3 columns]